Option Strict On
Option Explicit On
' استيراد المسارات التي تحتوي على الواجهات والمستودعات


Imports Student_Management_Initial.Student_Management_Initial.DLL
Imports Student_Management_Initial.Student_Management_Initial.Interface.DLL_Interface
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


'وظـــيفة هاذى الكلاس  ::'(MyApplication)
'حقن التبعية ونقطة الانطلاق
'يمثل كلاس MyApplication العقل المدبر الذي يدير لحظات الانطلاق الأولى عبر الإجراء OnCreateMainForm
'• تجهيز الأدوات: يتم إنشاء كائن المستودع (مثل StudentRepositorySql) أولاً
'• حقن التبعية (Dependency Injection): يقوم البرنامج بتمرير هذا المستودع إلى شاشة الدخول frmLogin أو الشاشة الرئيسية عند إنشائها
'• تحديد واجهة البداية: يقرر البرنامج هنا أي نافذة تظهر للمستخدم أولاً لتوجيه تدفق العمل بشكل صحي
'    
Namespace My

    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    ' or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click the My Project node in
    ' Solution Explorer), and make changes on the Application tab.
    '
    Partial Friend Class MyApplication

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = False
            Me.EnableVisualStyles = True
            Me.SaveMySettingsOnExit = True
            Me.ShutdownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
            Me.HighDpiMode = HighDpiMode.DpiUnaware
        End Sub
        '        هذه الدوال هي المكان الذي يتم فيه تهيئة التطبيق عند أول تشغيل (Initialization).
        'OnCreateMainForm
        'OnInitialize
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Protected Overrides Sub OnCreateMainForm() 'لكود المسؤول عن "حقن التبعية" في الملف   +  ' 🔥 استدعاء التهيئة لأول تشغيل

            '            هنا يتم بااستخدام خاصيةFirst Run Initialization 
            'بحيث يتم التالي 
            'هنا يحدث شيئين
            'إنشاء المستودع(repository): الكود يولّد نسخة من StudentRepositorySql.
            'حقن التبعية(Dependency Injection): بدل أن يقوم الفورم بنفسه بإنشاء المستودع داخليًا، يتم تمرير المستودع له كمعامل في الـ Constructor

            '👉 الفائدة:
            'فصل المسؤوليات، سهولة تبديل المستودع لاحقًا بدون تعديل الفورم.

            'تحديد أن شاشة الدخول هي الـ MainForm عند تشغيل البرنامج.

            'هذا بالضبط هو First Run Initialization: أي الكود الذي يحدد كيف يبدأ التطبيق عند أول تشغيل.

            'إنشاء المستودع وحقنه في الفورم الرئيسي
            Dim repository As IStudentRepository = New Student_Management_Initial.DLL.StudentRepositorySql() ' إنشاء المستودع وحقنه في الفورم الرئيسي
            ' 2. حقن التبعية: تمرير المستودع إلى الفورم عند إنشائه 
            ' هنا نخبر الفورم: "خذ هذا المستودع لتعمل به"
            'Me.MainForm = New frmStudentManagervb(repo)
            ' البداية الآن من شاشة الدخول
            Me.MainForm = New frmLogin(repository) 'هذا يعني أن الفورم يعتمد على المستودع لكنه لا يعرف تفاصيله (هل هو SQL أو LocalDB أو قائمة في الذاكرة).
        End Sub
        '        هذه الدوال هي المكان الذي يتم فيه تهيئة التطبيق عند أول تشغيل (Initialization).
        'OnCreateMainForm
        'OnInitialize
        '            هنا يتم بااستخدام خاصيةFirst Run Initialization 

        'هي دالة تعمل في مرحلة مبكرة جداً قبل إنشاء النموذج الرئيسي، وتُستخدم لإعدادات أولية مثل تحديد وقت عرض شاشة الترحيب (Splash Screen)
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Protected Overrides Function OnInitialize(ByVal commandLineArgs As System.Collections.ObjectModel.ReadOnlyCollection(Of String)) As Boolean
            Me.MinimumSplashScreenDisplayTime = 0
            Return MyBase.OnInitialize(commandLineArgs)
        End Function
    End Class
End Namespace
